import { Component, OnInit } from '@angular/core'; import { CommonModule } from '@angular/common'; import { FormsModule } from '@angular/forms'; import { Title, Meta } from '@angular/platform-browser'; import { RouterModule } from '@angular/router';
@Component({ selector: 'app-ai-summarizer', standalone: true, imports: [CommonModule, FormsModule, RouterModule], templateUrl: './ai-summarizer.component.html', styleUrls: ['./ai-summarizer.component.css'] })
export class AiSummarizerComponent implements OnInit {
  selectedFiles: File[] = []; isDragging = false; isConverting = false; progress = 0; convertedUrl: string | null = null; convertedBlob: Blob | null = null;
  summaryText = '';
  constructor(private title: Title, private meta: Meta) {} ngOnInit() { this.title.setTitle('AI PDF Summarizer – Smart Document Summary | ConverterAllAI'); this.meta.updateTag({ name: 'description', content: 'Get AI-powered summaries of your PDF documents.' }); }
  onDragOver(e: DragEvent) { e.preventDefault(); this.isDragging = true; } onDragLeave(e: DragEvent) { e.preventDefault(); this.isDragging = false; }
  onDrop(e: DragEvent) { e.preventDefault(); this.isDragging = false; if (e.dataTransfer?.files.length) this.addFiles(e.dataTransfer.files); }
  onFileSelected(e: Event) { const input = e.target as HTMLInputElement; if (input.files?.length) this.addFiles(input.files); }
  addFiles(files: FileList) { this.selectedFiles = [Array.from(files)[0]]; this.resetState(false); } removeFile(i: number) { this.selectedFiles.splice(i, 1); if (!this.selectedFiles.length) this.resetState(true); } hasSettings() { return false; }
  resetState(clearFiles = true) { this.convertedUrl = null; this.convertedBlob = null; this.progress = 0; this.isConverting = false; this.summaryText = ''; if (clearFiles) this.selectedFiles = []; }
  async processFiles() { if (!this.selectedFiles.length) return; this.isConverting = true; this.progress = 0;
    try {
      const pdfjsLib = await import('pdfjs-dist'); (pdfjsLib as any).GlobalWorkerOptions.workerSrc = '/assets/pdf.worker.min.mjs';
      this.progress = 15; const bytes = await this.selectedFiles[0].arrayBuffer(); const pdfDoc = await pdfjsLib.getDocument({ data: bytes }).promise; this.progress = 30;
      let fullText = ''; for (let i = 1; i <= Math.min(pdfDoc.numPages, 10); i++) { const page = await pdfDoc.getPage(i); const tc = await page.getTextContent(); fullText += tc.items.map((item: any) => item.str).join(' ') + ' '; this.progress = 30 + Math.round((40 / Math.min(pdfDoc.numPages, 10)) * i); }
      this.progress = 75;
      // Generate summary from extracted text
      const words = fullText.split(/\s+/).filter(w => w.length > 3);
      const sentences = fullText.split(/[.!?]+/).filter(s => s.trim().length > 20).slice(0, 8);
      this.summaryText = `📊 Document Summary: "${this.selectedFiles[0].name}"\n\n📄 Pages: ${pdfDoc.numPages}\n📝 Word Count: ~${words.length}\n\n📋 Key Points:\n${sentences.map((s, i) => `${i+1}. ${s.trim()}`).join('\n')}\n\n💡 This summary was generated by extracting and analyzing the text content from your PDF document.`;
      this.progress = 95; this.convertedBlob = new Blob([this.summaryText], { type: 'text/plain' }); this.convertedUrl = URL.createObjectURL(this.convertedBlob); this.progress = 100;
    } catch (err) { console.error(err); alert('Summarization failed.'); } this.isConverting = false; }
  copyToClipboard() { navigator.clipboard.writeText(this.summaryText).then(() => alert('Summary copied!')); }
  download() { if (!this.convertedBlob) return; const a = document.createElement('a'); a.href = URL.createObjectURL(this.convertedBlob); a.download = 'summary.txt'; a.click(); }
  formatBytes(bytes: number): string { if (bytes === 0) return '0 Bytes'; const k = 1024, s = ['Bytes','KB','MB','GB']; const i = Math.floor(Math.log(bytes)/Math.log(k)); return parseFloat((bytes/Math.pow(k,i)).toFixed(2))+' '+s[i]; }
}
