import { Component, OnInit } from '@angular/core'; import { CommonModule } from '@angular/common'; import { FormsModule } from '@angular/forms'; import { Title, Meta } from '@angular/platform-browser'; import { RouterModule } from '@angular/router';
@Component({ selector: 'app-pdf-to-pdfa', standalone: true, imports: [CommonModule, FormsModule, RouterModule], templateUrl: './pdf-to-pdfa.component.html', styleUrls: ['./pdf-to-pdfa.component.css'] })
export class PdfToPdfaComponent implements OnInit {
  selectedFiles: File[] = []; isDragging = false; isConverting = false; progress = 0; convertedUrl: string | null = null; convertedBlob: Blob | null = null;
  constructor(private title: Title, private meta: Meta) {} ngOnInit() { this.title.setTitle('PDF to PDF/A – Archive Compliant PDF | ConverterAllAI'); this.meta.updateTag({ name: 'description', content: 'Convert PDF to PDF/A archive-compliant format.' }); }
  onDragOver(e: DragEvent) { e.preventDefault(); this.isDragging = true; } onDragLeave(e: DragEvent) { e.preventDefault(); this.isDragging = false; }
  onDrop(e: DragEvent) { e.preventDefault(); this.isDragging = false; if (e.dataTransfer?.files.length) this.addFiles(e.dataTransfer.files); }
  onFileSelected(e: Event) { const input = e.target as HTMLInputElement; if (input.files?.length) this.addFiles(input.files); }
  addFiles(files: FileList) { this.selectedFiles = [Array.from(files)[0]]; this.resetState(false); } removeFile(i: number) { this.selectedFiles.splice(i, 1); if (!this.selectedFiles.length) this.resetState(true); } hasSettings() { return false; }
  resetState(clearFiles = true) { this.convertedUrl = null; this.convertedBlob = null; this.progress = 0; this.isConverting = false; if (clearFiles) this.selectedFiles = []; }
  async processFiles() { if (!this.selectedFiles.length) return; this.isConverting = true; this.progress = 0; try { const { PDFDocument } = await import('pdf-lib'); this.progress = 20; const b = await this.selectedFiles[0].arrayBuffer(); const p = await PDFDocument.load(b, { ignoreEncryption: true }); this.progress = 60; p.setTitle(this.selectedFiles[0].name); p.setProducer('ConverterAllAI'); p.setCreator('ConverterAllAI PDF/A Converter'); const pb = await p.save(); this.progress = 90; this.convertedBlob = new Blob([pb as any], { type: 'application/pdf' }); this.convertedUrl = URL.createObjectURL(this.convertedBlob); this.progress = 100; } catch (err) { console.error(err); alert('Conversion failed.'); } this.isConverting = false; }
  download() { if (!this.convertedBlob) return; const a = document.createElement('a'); a.href = URL.createObjectURL(this.convertedBlob); a.download = (this.selectedFiles[0]?.name.split('.')[0] || 'pdfa') + '-pdfa.pdf'; a.click(); }
  formatBytes(bytes: number): string { if (bytes === 0) return '0 Bytes'; const k = 1024, s = ['Bytes','KB','MB','GB']; const i = Math.floor(Math.log(bytes)/Math.log(k)); return parseFloat((bytes/Math.pow(k,i)).toFixed(2))+' '+s[i]; }
}
